image: ubuntu

environment:
  SITE_REPO_TOKEN: 
    secure: 9J4+3PqRqzTDiC280JthRE4EVP8YqK67eEDJmyD+2s+j8H/R5TyrJJJNnpOejxCH

install:
- sh: sudo rm -rf /var/lib/apt/lists/*
- sh: sudo apt-get update
- sh: sudo apt-get -y install curl
- sh: \curl -L https://get.rvm.io | bash -s stable --ruby
- sh: rvm reload
- sh: rvm get stable --autolibs=enable
- sh: rvm install ruby
- sh: gem install jekyll bundler

build_script:
- sh: cd src
- sh: bundle install
- sh: git config --global credential.helper "store --file ~/.git-credentials"
- ps: git config --global user.email $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL
- ps: git config --global user.name $env:APPVEYOR_REPO_COMMIT_AUTHOR
- ps: Add-Content "~/.git-credentials" "https://$($env:SITE_REPO_TOKEN):x-oauth-basic@github.com"
- ps: | 
    # Se for um pull-request, então não tem como obter as secure variables
    # https://help.appveyor.com/discussions/problems/456-encrypted-environment-variables-not-set-for-pull-request-builds
    # Nesses casos apenas realiza o build do Jekyll, mas não atualiza o site staging
    if (!$env:APPVEYOR_PULL_REQUEST_NUMBER)
    {
      # Se for branch 'master', então publica no https://jogosdaqui.gitub.io
      # caso não seja qualquer outro branch, então publica no staging: https://jogosdaqui.github.io/jogosdaqui.github.io-staging
      if ($env:APPVEYOR_REPO_BRANCH -eq "master") {
        echo 'O repositório de produção será atualizado.'
        git clone https://github.com/jogosdaqui/jogosdaqui.github.io.git _site
      } else {
        echo 'O repositório de staging será atualizado.'
        git clone https://github.com/jogosdaqui/jogosdaqui.github.io-staging.git _site
      }
    
      # Se não for branch 'master', então altera o arquivo _config.yml para utilizar o staging.
      if ($env:APPVEYOR_REPO_BRANCH -ne "master") {
        sed -i -e 's/jogosdaqui\.github\.io/jogosdaqui\.github\.io\/jogosdaqui\.github\.io\-staging/g' _config.yml
        sed -i -e 's/name: jogosdaqui/name: jogosdaqui (STAGING)/g' _config.yml
        sed -i -e 's/baseurl: \"\"/baseurl: "\/jogosdaqui\.github\.io-staging"/g' _config.yml
        sed -i -e 's/description: A maior fonte colaborativa sobre games desenvolvidos no Brasil/description: STAGING STAGING STAGING STAGING STAGING STAGING/g' _config.yml
        cat _config.yml
        rm -f robots.txt
        echo 'User-agent: *' > robots.txt
        echo 'Disallow: /' >> robots.txt
      } 
    }
- sh: cd ..
- sh: ./generate-bundle.sh
- sh: cd src
- sh: bundle exec jekyll build
 
- ps: | 
    if (!$env:APPVEYOR_PULL_REQUEST_NUMBER)
    {
      cd _site
      echo "{ `"date`": `"$(Get-Date -Format g)`", `"branch`": `"$($env:APPVEYOR_REPO_BRANCH)`" }" > version.json
      git add .
      git commit -m "$($env:APPVEYOR_REPO_COMMIT_MESSAGE)"
      git push
    }