source 'https://rubygems.org'

gem 'jekyll', '3.8.5', group: :jekyll_plugins
gem 'jekyll-sitemap'
gem 'jekyll-feed'
gem 'jekyll-tagging'
gem 'jekyll-paginate-v2'
gem 'tzinfo-data'
gem 'jekyll-minifier'